# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Arch Linux's package action"
description: "GitHub Action to run Arch Linux's package tools"
author: 'heyhusen'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  path:
    description: 'Location for this action to run'
    default: ''
    required: false
  pkgver:
    description: 'Update pkgver on PKGBUILD'
    default: ''
    required: false
  pkgrel:
    description: 'Update pkgrel on PKGBUILD'
    default: ''
    required: false
  updpkgsums:
    description: 'Update checksums on PKGBUILD'
    default: 'false'
    required: false
  srcinfo:
    description: 'Generate new .SRCINFO'
    default: 'false'
    required: false
  flags:
    description: 'Extra flags for makepkg'
    default: '-cfs --noconfirm'
    required: false
  namcap:
    description: 'Validate package with namcap'
    default: 'true'
    required: false
  aur:
    description: 'Resolve dependencies using paru'
    default: 'false'
    required: false
  archlinux_keyring:
    description: 'Update archlinux-keyring'
    default: 'true'
    required: false
  pgpkeys:
    description: 'Comma-separated pgp keys'
    default: ''
    required: false
  pgpkeyserver:
    description: 'PGP key server'
    default: 'hkps://keyserver.ubuntu.com'
    required: false

runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.path }}
    - ${{ inputs.pkgver }}
    - ${{ inputs.pkgrel }}
    - ${{ inputs.updpkgsums }}
    - ${{ inputs.srcinfo }}
    - ${{ inputs.flags }}
    - ${{ inputs.namcap }}
    - ${{ inputs.aur }}
    - ${{ inputs.archlinux_keyring }}
    - ${{ inputs.pgpkeys }}
    - ${{ inputs.pgpkeyserver }}
